version: '3.3'

services:
  app:
    build: ./php-apache
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html:delegated
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mastertax
      DB_USERNAME: master
      DB_PASSWORD: master
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - mastertax-net

  node:
    build: ./node-api
    container_name: node-service
    ports:
      - "3000:3000"
    volumes:
      - ./node-scripts:/usr/src/app:delegated
    working_dir: /usr/src/app
    command: ["node", "index.js"]
    depends_on:
      - app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mastertax-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mastertax
      MYSQL_USER: master
      MYSQL_PASSWORD: master
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mastertax-net

volumes:
  db_data:

networks:
  mastertax-net:
    driver: bridge
