global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'laravel'
    metrics_path: '/metrics'  # Verifique se sua aplicação expõe aqui
    static_configs:
      - targets: ['app:80']

  - job_name: 'node_service'
    metrics_path: '/metrics'  # Ajuste se necessário
    static_configs:
      - targets: ['node:3000']
